'use client'

import { ChangeEvent, RefObject, useEffect, useRef, useState } from 'react'
import { toPng } from 'html-to-image'
import { Camera, Download, ImagePlus, Link2, Plus, RotateCcw, Sparkles, Trash2, Users, ZoomIn, ZoomOut } from 'lucide-react'

type Mode = 'solo' | 'team'
type Theme = 'palm-house' | 'sunset-signal' | 'studio-night'
type Member = { name: string; id: string; handle: string; photo?: string; uid: string }

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Vq56N0ls7VXHNT3HLkEwfBp4ZVsczj.png'
const themes = {
  'palm-house': { label: 'Palm House Pass', accent: '#ffe500', hot: '#ff0b78', paper: '#f7f1d7', ink: '#073b2a', background: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-09%20135149-6e9SeyhJolS94ZfmPgCheK9MhPj4Bz.png' },
  'sunset-signal': { label: 'Sunset Signal', accent: '#ff0b78', hot: '#ffe500', paper: '#fffdf5', ink: '#073b2a', background: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-08-09%20135213-NtjOEQoFNG8ZpE36zjW8WrMkaslw3w.png' },
  'studio-night': { label: 'Studio Night', accent: '#00d9b5', hot: '#ff0b78', paper: '#071b17', ink: '#fffdf5', background: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7hCfQCAs6T8gPGXWHuid4n4NjkdUiO.png' },
} as const
const eventMeta = 'GOA, INDIA · 28–31 OCT 2026'
const makeMember = (): Member => ({ name: '', id: '', handle: '', uid: crypto.randomUUID() })
const initialMember = makeMember()

function initials(value: string) { return value.trim().split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'HH' }
function cleanHandle(value: string) { return value.replace(/^@+/, '') }
function barcodePattern(value: string) { return Array.from({ length: 36 }, (_, index) => ((value.charCodeAt(index % Math.max(1, value.length)) || 37) + index * 17) % 5 + 1) }
function Barcode({ value }: { value: string }) { return <div className="barcode-wrap" aria-label={`Barcode for ${value}`}><div className="barcode">{barcodePattern(value).map((width, index) => <i key={`${value}-${index}`} style={{ width: `${width}px` }} />)}</div><span>{value}</span></div> }
function Field({ label, value, onChange, placeholder, maxLength }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; maxLength: number }) { return <label className="flex flex-col gap-2"><span className="form-label">{label}</span><input className="form-input" value={value} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label> }

function PhotoUploader({ image, onImage, zoom, setZoom, offset, setOffset }: { image: string | null; onImage: (event: ChangeEvent<HTMLInputElement>) => void; zoom: number; setZoom: (value: number) => void; offset: { x: number; y: number }; setOffset: (value: { x: number; y: number }) => void }) {
  const fileRef = useRef<HTMLInputElement>(null)
  return <section className="form-panel"><div className="form-section-title"><ImagePlus data-icon="inline-start" /> 1. BUILDER PHOTO <span className="form-status">JPG / PNG / HEIC · 12MB MAX</span></div><input ref={fileRef} hidden type="file" accept="image/*,.heic,.heif" onChange={onImage} /><button type="button" className="upload-dropzone mt-4" onClick={() => fileRef.current?.click()}>{image ? <><Camera data-icon="inline-start" /> Replace photo</> : <><ImagePlus data-icon="inline-start" /> Upload photo</>}</button>{image && <div className="crop-panel"><div className="flex items-center justify-between"><span className="form-label">AUTO-CENTERED PHOTO</span><span className="form-status">{Math.round(zoom * 100)}%</span></div><input aria-label="Photo zoom" type="range" min="1" max="2.5" step=".05" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /><div className="flex gap-2"><button type="button" className="mini-button" onClick={() => setZoom(Math.max(1, zoom - .1))}><ZoomOut /> Zoom out</button><button type="button" className="mini-button" onClick={() => setZoom(Math.min(2.5, zoom + .1))}><ZoomIn /> Zoom in</button><button type="button" className="mini-button" onClick={() => { setZoom(1); setOffset({ x: 50, y: 50 }) }}><RotateCcw /> Reset</button></div><div className="flex gap-2"><button type="button" className="mini-button" onClick={() => setOffset({ ...offset, x: Math.max(0, offset.x - 5) })}>←</button><button type="button" className="mini-button" onClick={() => setOffset({ ...offset, x: Math.min(100, offset.x + 5) })}>→</button><button type="button" className="mini-button" onClick={() => setOffset({ ...offset, y: Math.max(0, offset.y - 5) })}>↑</button><button type="button" className="mini-button" onClick={() => setOffset({ ...offset, y: Math.min(100, offset.y + 5) })}>↓</button></div></div>}</section>
}

function SoloForm({ solo, setSolo }: { solo: Member; setSolo: (value: Member) => void }) { return <section className="form-panel"><div className="form-section-title"><Sparkles /> 2. SOLO PROFILE</div><div className="mt-4 flex flex-col gap-4"><Field label="NAME" value={solo.name} onChange={(name) => setSolo({ ...solo, name })} placeholder="e.g. Anubhav" maxLength={32} /><Field label="MEMBER ID" value={solo.id} onChange={(id) => setSolo({ ...solo, id })} placeholder="e.g. HHG-0247" maxLength={20} /><Field label="X / SOCIAL HANDLE" value={solo.handle} onChange={(handle) => setSolo({ ...solo, handle })} placeholder="e.g. anubhavsdk" maxLength={24} /></div></section> }

function TeamForm({ teamName, setTeamName, teamHandle, setTeamHandle, members, updateMember, addMember, removeMember }: { teamName: string; setTeamName: (value: string) => void; teamHandle: string; setTeamHandle: (value: string) => void; members: Member[]; updateMember: (index: number, key: keyof Member, value: string) => void; addMember: () => void; removeMember: (index: number) => void }) { return <section className="form-panel"><div className="form-section-title"><Users /> 2. SQUAD PROFILE</div><div className="mt-4 flex flex-col gap-4"><Field label="TEAM NAME" value={teamName} onChange={setTeamName} placeholder="e.g. DARQlords" maxLength={30} /><Field label="TEAM / X HANDLE" value={teamHandle} onChange={setTeamHandle} placeholder="e.g. DARQlords_Goa" maxLength={24} />{members.map((member, index) => <div className="member-editor flex flex-col gap-3" key={member.uid}><div className="flex items-center justify-between"><span className="form-label">MEMBER {index + 1}</span>{members.length > 1 && <button type="button" className="icon-button" onClick={() => removeMember(index)} aria-label={`Remove member ${index + 1}`}><Trash2 /></button>}</div><Field label="NAME" value={member.name} onChange={(value) => updateMember(index, 'name', value)} placeholder="Builder name" maxLength={32} /><Field label="MEMBER ID" value={member.id} onChange={(value) => updateMember(index, 'id', value)} placeholder="HHG-0247" maxLength={20} /><Field label="HANDLE" value={member.handle} onChange={(value) => updateMember(index, 'handle', value)} placeholder="builder_handle" maxLength={24} /></div>)}<button type="button" className="add-button" onClick={addMember} disabled={members.length >= 4}><Plus /> Add teammate</button></div></section> }

function ThemePicker({ theme, setTheme }: { theme: Theme; setTheme: (value: Theme) => void }) { return <section className="form-panel"><div className="form-section-title">3. BADGE VISUAL THEME</div><div className="theme-grid mt-4">{(Object.entries(themes) as [Theme, (typeof themes)[Theme]][]).map(([key, value]) => <button type="button" key={key} onClick={() => setTheme(key)} className={`theme-choice ${theme === key ? 'selected' : ''}`} style={{ background: value.paper, color: value.ink, borderColor: value.hot }}><span>{value.label}</span><i style={{ background: value.accent }} /></button>)}</div></section> }

function CredentialPreview({ mode, theme, solo, teamName, teamHandle, members, image, zoom, offset, teamCode, cardRef }: { mode: Mode; theme: Theme; solo: Member; teamName: string; teamHandle: string; members: Member[]; image: string | null; zoom: number; offset: { x: number; y: number }; teamCode: string; cardRef: RefObject<HTMLDivElement | null> }) { const t = themes[theme]; const visibleMembers = members.filter((member) => member.name.trim()); const displayName = mode === 'team' ? teamName || 'YOUR SQUAD' : solo.name || 'YOUR NAME'; const displayId = mode === 'team' ? teamCode : solo.id || 'HHG-0247'; const displayHandle = mode === 'team' ? cleanHandle(teamHandle) : cleanHandle(solo.handle); return <div className="credential-stage"><div className="stage-topline"><span>LIVE CREDENTIAL PREVIEW</span><span>{t.label}</span></div><div ref={cardRef} className="id-card-shell" style={{ ['--id-accent' as string]: t.accent, ['--id-hot' as string]: t.hot, ['--id-paper' as string]: t.paper, ['--id-ink' as string]: t.ink, backgroundImage: `linear-gradient(120deg, color-mix(in srgb, ${t.paper} 86%, transparent), color-mix(in srgb, ${t.paper} 58%, transparent)), url(${t.background})`, backgroundSize: 'cover', backgroundPosition: 'center' }}><div className="id-card-scanline" /><div className="id-card-header"><div><p className="id-kicker">HACKER HOUSE GOA · BUILDER PASS</p><p className="id-kicker">{eventMeta}</p></div><img className="id-card-logo" src={logoUrl} alt="Hacker House Goa logo" /></div>{mode === 'solo' ? <div className="id-card-body"><div className="id-photo">{image ? <img src={image} alt="Uploaded builder portrait" style={{ transform: `scale(${zoom})`, objectPosition: `${offset.x}% ${offset.y}%` }} /> : initials(displayName)}</div><div><p className="id-kicker">RESIDENT BUILDER</p><h2 className="id-name">{displayName}</h2><p className="id-handle">@{displayHandle || 'your_handle'}</p><div className="id-details"><span><b>MEMBER ID</b>{solo.id || 'HHG-0247'}</span><span><b>STACK</b>BUILD / SHIP</span><span><b>PLACE</b>GOA</span></div></div></div> : <div className="id-team-body"><div className="id-team-top"><div className="id-crest">{initials(displayName)}</div><div><p className="id-kicker">SQUAD CREDENTIAL</p><h2 className="id-name">{displayName}</h2><p className="id-handle">@{displayHandle || 'team_handle'}</p></div></div><div className="id-member-grid">{visibleMembers.length ? visibleMembers.map((member) => <div className="id-member-tile" key={member.uid}><b>{member.name}</b><span>{member.id || 'MEMBER ID'}</span><span>@{cleanHandle(member.handle) || 'handle'}</span></div>) : <div className="id-empty">ADD YOUR BUILDERS TO POPULATE THE SQUAD PASS</div>}</div></div>}<div className="id-card-footer"><span>#FRAMEINGOA · 2:47 PM STUDIO</span><Barcode value={displayId} /></div></div></div> }

function ExportControls({ ready, exporting, error, download, share }: { ready: boolean; exporting: boolean; error: string; download: () => void; share: () => void }) { return <div className="preview-actions"><button type="button" className="primary-action" disabled={!ready || exporting} onClick={download}>{exporting ? 'Exporting…' : <><Download /> Download PNG</>}</button><button type="button" className="secondary-action" disabled={!ready} onClick={share}><Link2 /> Share to X</button>{error && <p role="alert" className="form-status text-destructive">{error}</p>}</div> }

export function UnifiedIdGenerator() {
  const [mode, setMode] = useState<Mode>('solo'); const [theme, setTheme] = useState<Theme>('palm-house'); const [solo, setSolo] = useState<Member>(initialMember); const [teamName, setTeamName] = useState(''); const [teamHandle, setTeamHandle] = useState(''); const [members, setMembers] = useState<Member[]>([makeMember(), makeMember()]); const [image, setImage] = useState<string | null>(null); const [zoom, setZoom] = useState(1); const [offset, setOffset] = useState({ x: 50, y: 50 }); const [exporting, setExporting] = useState(false); const [exportError, setExportError] = useState(''); const [switching, setSwitching] = useState(false); const [teamCode] = useState(() => `HHG-${Math.random().toString(36).slice(2, 8).toUpperCase()}`); const cardRef = useRef<HTMLDivElement>(null); const visibleMembers = members.filter((member) => member.name.trim()); const ready = mode === 'solo' ? Boolean(solo.name.trim()) : Boolean(teamName.trim() && visibleMembers.length)
  function switchMode(next: Mode) { if (next === mode) return; setSwitching(true); window.setTimeout(() => { setMode(next); setSwitching(false) }, 320) }
  async function handleImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const heic = /heic|heif/i.test(file.type) || /\.(heic|heif)$/i.test(file.name); if ((!file.type.startsWith('image/') && !heic) || file.size > 12 * 1024 * 1024) { setExportError('Upload an image or HEIC file under 12MB.'); return } try { const converted = heic ? await (await import('heic2any')).default({ blob: file, toType: 'image/jpeg', quality: .92 }) : file; const blob = Array.isArray(converted) ? converted[0] : converted; setImage(URL.createObjectURL(blob)); setZoom(1); setOffset({ x: 50, y: 50 }); setExportError('') } catch { setExportError('This photo could not be converted. Try a JPG or PNG.') } }
  function updateMember(index: number, key: keyof Member, value: string) { setMembers((current) => current.map((member, item) => item === index ? { ...member, [key]: value } : member)) }
  function addMember() { setMembers((current) => [...current, makeMember()]) }
  function removeMember(index: number) { setMembers((current) => current.filter((_, item) => item !== index)) }
  function shareOnX() { const subject = mode === 'team' ? teamName || 'our HH Goa team' : solo.name || 'my HH Goa ID'; const text = `I just made my Hacker House Goa ID as ${subject}. See you in Goa. #FrameInGoa`; window.open(`https://x.com/intent/post?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer') }
  async function download() { if (!cardRef.current) return; setExporting(true); setExportError(''); try { const dataUrl = await toPng(cardRef.current, { pixelRatio: 2, cacheBust: true }); const link = document.createElement('a'); link.download = `hh-goa-${mode}-id.png`; link.href = dataUrl; link.click() } catch (error) { console.error('[v0] card export failed', error); setExportError('Could not export this card. Please try again.') } finally { setExporting(false) } }
  useEffect(() => () => { if (image) URL.revokeObjectURL(image) }, [image])
  return <main className="min-h-screen bg-background pb-16 text-foreground"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><div className="flex items-center gap-3"><img src={logoUrl} alt="Hacker House Goa logo" className="size-12 border-2 border-foreground object-cover" /><div><p className="font-mono text-xs font-black tracking-[.18em]">HACKER HOUSE GOA</p><p className="font-mono text-[10px] font-bold text-muted-foreground">2:47 PM STUDIO · ID MAKER</p></div></div><span className="hidden font-mono text-[10px] font-bold text-muted-foreground md:block">{eventMeta} / #FRAMEINGOA</span></header><section className="mx-auto max-w-7xl px-5 pt-8 md:px-10 md:pt-12"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="font-mono text-xs font-black tracking-[.2em] text-muted-foreground">OFFICIAL EVENT CREDENTIAL</p><h1 className="mt-4 text-balance text-5xl font-black uppercase leading-[.86] tracking-[-.07em] md:text-8xl">WEAR YOUR<br /><span className="text-secondary">BUILD.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-muted-foreground">Make a real Hacker House Goa pass for your pocket, your team, and your feed.</p></div><div className="mode-switch-wrap-static"><span className="form-label">CHOOSE CREDENTIAL TYPE</span><div className="mode-switch-static" data-mode={mode}><span className="mode-switch-track-static" /><button type="button" onClick={() => switchMode('solo')} className={`mode-button-static ${mode === 'solo' ? 'active' : ''}`} aria-pressed={mode === 'solo'}><Sparkles /> SOLO ID</button><button type="button" onClick={() => switchMode('team')} className={`mode-button-static ${mode === 'team' ? 'active' : ''}`} aria-pressed={mode === 'team'}><Users /> TEAM ID</button></div></div></div><div className={`mt-12 grid gap-10 lg:grid-cols-[340px_1fr] ${switching ? 'mode-glitching' : 'mode-ready'}`}><div className="flex flex-col gap-5"><PhotoUploader image={image} onImage={handleImage} zoom={zoom} setZoom={setZoom} offset={offset} setOffset={setOffset} />{mode === 'solo' ? <SoloForm solo={solo} setSolo={setSolo} /> : <TeamForm teamName={teamName} setTeamName={setTeamName} teamHandle={teamHandle} setTeamHandle={setTeamHandle} members={members} updateMember={updateMember} addMember={addMember} removeMember={removeMember} />}<ThemePicker theme={theme} setTheme={setTheme} /></div><div className="preview-column"><CredentialPreview mode={mode} theme={theme} solo={solo} teamName={teamName} teamHandle={teamHandle} members={members} image={image} zoom={zoom} offset={offset} teamCode={teamCode} cardRef={cardRef} /><ExportControls ready={ready} exporting={exporting} error={exportError} download={download} share={shareOnX} /></div></div></section></main>
}
